### ISSUE TITLE
Fix joyractor new post format

### ISSUE THREAD

**Issue by Aristarhys** [ChaikaBogdan/memes2telegram#143]
https://joyreactor.cc/post/5969080
![image](https://github.com/user-attachments/assets/c5f931e6-7a0e-48f8-ad68-2049ef62c374)

**Comment by ChaikaBogdan** [comment]
`batches ['https://img2.joyreactor.cc/pics/post/RimWorld-Игры-C-M-Y-K-8688535.jpeg', 'https://img2.joyreactor.cc/pics/post/RimWorld-Игры-C-M-Y-K-8688536.jpeg']
media [InputMediaPhoto(caption='https://joyreactor.cc/post/5969080', has_spoiler=False, media='https://img2.joyreactor.cc/pics/post/RimWorld-Игры-C-M-Y-K-8688535.jpeg', type=<InputMediaType.PHOTO>), InputMediaPhoto(has_spoiler=False, media='https://img2.joyreactor.cc/pics/post/RimWorld-Игры-C-M-Y-K-8688536.jpeg', type=<InputMediaType.PHOTO>)]`
![b0f7deec-f239-4a5a-ab8e-143b9632964f_text](https://github.com/user-attachments/assets/b6b88669-e06c-4a1a-a232-10821df170cd)
