### ISSUE TITLE
Unwrap short DTF links to long ones

### ISSUE THREAD

**Issue by ChaikaBogdan** [ChaikaBogdan/memes2telegram#93]
https://dtf.ru/2830774 - > https://dtf.ru/life/2830774-microsoft-odin-iz-sposobov-ustranit-sboi-crowdstrike-vyklyuchit-i-vklyuchit-sistemu-do-15-raz

**Comment by Aristarhys** [comment]
Не возможно сделать - https://dtf.ru/2830774 == 404 происходит какая то магия на фронте
